### ISSUE TITLE
KeyError: 3.1

### ISSUE THREAD

**Issue by lemairecarl** [ComputeCanada/avail_wheels#14]
In a python 3.10 virtualenv on Narval:
```
$ avail_wheels wrapt
Traceback (most recent call last):
  File "/cvmfs/soft.computecanada.ca/custom/bin/avail_wheels", line 351, in <module>
    main()
  File "/cvmfs/soft.computecanada.ca/custom/bin/avail_wheels", line 328, in main
    wheels = get_wheels(search_paths, names_versions=names_versions, pythons=pythons, latest=latest)
  File "/cvmfs/soft.computecanada.ca/custom/bin/avail_wheels", line 134, in get_wheels
    if is_compatible(wheel, pythons):
  File "/cvmfs/soft.computecanada.ca/custom/bin/avail_wheels", line 96, in is_compatible
    if wheel.python in COMPATIBLE_PYTHON[p]:
KeyError: '3.1'
```

**Comment by ccoulombe** [comment]
Fixed on the systems. This issue does not happen with 2.0
